### ISSUE TITLE
validator

### ISSUE THREAD

**Issue by mukhammadyn** [faithpacifica/position-related-tasks#2]
![image](https://user-images.githubusercontent.com/77844899/147777976-8be1c877-1633-40a3-9abb-a74c0d6aeb5c.png)

:((

**Comment by faithpacifica** [comment]
[](url)
hamma xatolarni tugirladim lekin mendan sectionda heading quyishin kere deb surab yotibdi shu momentini tushunmadim
komment da h2 yozib quygan bulsam ham tan olmayapti
